import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
function App() {
  const barChartRef = useRef(null);
  const pieChartRef = useRef(null);


useEffect(() => {
  const barChartCtx = barChartRef.current?.getContext('2d');
  const pieChartCtx = pieChartRef.current?.getContext('2d');

  // Destrói gráficos anteriores se existirem
  if (window.barChartInstance) {
    window.barChartInstance.destroy();
  }
  if (window.pieChartInstance) {
    window.pieChartInstance.destroy();
  }

  const barChartData = {
    labels: ['SAB', 'DOM', 'SEG', 'TER', 'QUA', 'QUI', 'SEX'],
    datasets: [
      {
        label: 'Usabilidade Semanal',
        data: [65, 59, 80, 81, 56, 55, 40],
        backgroundColor: 'rgba(63, 110, 164, 0.7)',
        borderColor: 'rgba(63, 110, 164, 1)',
        borderWidth: 1,
      },
    ],
  };

  const pieChartData = {
    labels: ['Concluído', 'Em Progresso', 'Não Iniciado'],
    datasets: [
      {
        data: [30, 50, 20],
        backgroundColor: ['#36a2eb', '#ffcd56', '#ff6384'],
        borderColor: '#ffffff',
      },
    ],
  };

  window.barChartInstance = new Chart(barChartCtx, {
    type: 'bar',
    data: barChartData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
    },
  });

  window.pieChartInstance = new Chart(pieChartCtx, {
    type: 'pie',
    data: pieChartData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
    },
  });
}, [])};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="layout">
      <aside className="sidebar">
        <div className="logo">
          <h2>HEALTH BOOK</h2>
        </div>
        <div className="sidebar-items">
          <button className="qr-code-button">QR Code</button>
          <div className="icons">
            <div className="icon">
              <img src=".img/hat-icon.jpg" alt="Estudos" />
            </div>
            <div className="icon">
              <img src="chat-icon.png" alt="Fórum" />
            </div>
            <div className="icon">
              <img src="internet-icon.png" alt="Pesquisas" />
            </div>
          </div>
        </div>
      </aside>

      
    </div>
        {children}</body>
    </html>
  )
}
